# 预制背景图脚本
# Generated by ChatGPT

import cv2
import numpy as np
import os

# 创建output文件夹
output_dir = 'output2'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# 定义模糊核大小
kernel_size = (411, 319)

# 遍历当前目录下的所有文件
for filename in os.listdir('.'):
    if filename.endswith('.webp'):
        # 读取图片
        img = cv2.imread(filename)
        
        # 应用高斯模糊
        blurred_img = cv2.GaussianBlur(img, kernel_size, 0)
        
        # 构建输出文件路径
        output_path = os.path.join(output_dir, filename)
        
        # 保存处理后的图片
        cv2.imwrite(output_path.replace('webp', 'png'), blurred_img)
        
        print(f'Processed and saved: {output_path}')

print('All images processed and saved to output folder.')
